export let baseUrl = "https://mernweekdays3backendecommerce.onrender.com"
export let signupUrl = "/users/signup"
export let loginUrl = "/users/login"
export let getUrl = "/users"
export let logoutUrl = "/users/logout"
export let updateUrl = "/users/update"
