export let baseUrl = "http://localhost:8000"
export let signupUrl = "/users/signup"
export let loginUrl = "/users/login"
export let getUrl = "/users"
export let logoutUrl = "/users/logout"
export let updateUrl = "/users/update"
